# Generated by Django 6.0.7 on 2026-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('review_pending', 'Review pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='uploaded', max_length=32)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt', max_length=8)),
                ('test_type', models.CharField(choices=[('compactacao_cbr', 'Compactação / CBR'), ('granulometria', 'Granulometria'), ('ambos', 'Ambos')], default='ambos', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_files', models.JSONField(blank=True, default=list)),
                ('openai_raw_response', models.JSONField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('reviewed_data', models.JSONField(blank=True, default=dict)),
                ('output_files', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
